"""SU2 8.0.1 fine members of the frozen, resolved-cap NASA mesh family.

Geometry and configuration are generated by seeb_resolved.run(mesh_only=True).
No SU2 8.5.0 solution is generated or claimed as a reference for these meshes.
"""
from pathlib import Path
import argparse,json,os,subprocess,time
import seeb_reference as base
import seeb_resolved as resolved
from install_su2_801 import BINARY_SHA256,ASSET_SHA256,URL
ROOT=Path(__file__).resolve().parents[2]
SOURCES=['seeb_family_v801.py','seeb_resolved.py','seeb_reference.py','cfd.py','analyze.py','install_su2_801.py']


def run(level,iterations=8000,mesh_only=False):
    if level not in (1.5,2.):raise ValueError('Only predeclared levels 1.5 and 2')
    if iterations!=8000:raise ValueError('This family has a fixed 8000-iteration ceiling')
    exe=Path(os.environ.get('SU2_CFD',str(ROOT/'.tools/week16_su2_801/bin/SU2_CFD'))).resolve()
    if base.sha256(exe)!=BINARY_SHA256:raise ValueError('Not the pinned official SU2 8.0.1 binary')
    name=f'seeb_resolved_v801_level_{level:g}'
    folder=ROOT/'results/week16_lowboom/reference'/name
    if folder.exists():raise FileExistsError(f'Output already exists: {folder}')
    sources={n:base.sha256(ROOT/'qa/week16'/n) for n in SOURCES}
    failure=None;meta={'level':level,'status':'meshing','converged':False,'source_sha256':sources}
    try:
        generated=resolved.run(level=level,iterations=iterations,threads=4,mesh_only=True,name=name)
        # Preserve original mesh-only generation provenance explicitly.
        base.atomic_json(folder/'mesh_generation.json',generated)
        meta=dict(generated)
        meta.update(solver_version='8.0.1',solver_binary_sha256=BINARY_SHA256,
                    official_asset_url=URL,official_asset_sha256=ASSET_SHA256,
                    mesh_generation_mode='Fresh mesh and configuration only; no prior CFD solution',
                    mesh_generating_source_sha256=generated['source_sha256'],source_sha256=sources,
                    threads=4,full_reference_validation_at_generation=False,
                    scope='Fine member of frozen resolved-cap family; full acceptance requires all three mesh levels and independent NASA comparison.')
        meta['sha256']['mesh_generation.json']=base.sha256(folder/'mesh_generation.json')
        if mesh_only:
            meta['status']='mesh_only';base.atomic_json(folder/'metadata.json',meta)
            return meta
        meta['status']='running';base.atomic_json(folder/'metadata.json',meta)
        start=time.time();env={**os.environ,'OMP_NUM_THREADS':'4','OPENBLAS_NUM_THREADS':'1'}
        with (folder/'solver.log').open('w') as log:
            proc=subprocess.run([str(exe),'flow.cfg','-t','4'],cwd=folder,env=env,stdout=log,stderr=subprocess.STDOUT)
            log.flush();os.fsync(log.fileno())
        meta.update(returncode=proc.returncode,wall_seconds=time.time()-start)
        if proc.returncode:raise RuntimeError(f'SU2 exited {proc.returncode}; see retained solver.log')
        meta.update(base.extract(folder))
        meta['converged']=bool(meta['density_residual_log10']<=-9 and meta['residual_drop']>=5 and meta['drag_tail_relative_range']<1e-4)
        meta['status']='converged' if meta['converged'] else 'not_converged'
        meta['sha256'].update({n:base.sha256(folder/n) for n in ['history.csv','restart_flow.csv','signature.npz','solver.log']})
        base.atomic_json(folder/'metadata.json',meta);base.verify_run(folder)
    except BaseException as exc:
        failure=exc;meta['status']='failed';meta['error']=f'{type(exc).__name__}: {exc}'
    finally:
        if folder.exists():
            if not mesh_only:
                try:audit=resolved.physical_audit(folder)
                except Exception as exc:audit={'passed':False,'error':str(exc),'checks':{'physical_fields_available_and_readable':False}}
                base.atomic_json(folder/'physical_audit.json',audit)
                meta['physical_plausibility_passed']=audit['passed'];meta['physical_audit_sha256']=base.sha256(folder/'physical_audit.json')
                if meta.get('converged') and not audit['passed']:meta['status']='physical_validation_failed'
            meta.setdefault('sha256',{}).update({p.name:base.sha256(p) for p in folder.iterdir() if p.is_file() and p.name not in ['metadata.json','metadata.json.partial']})
            meta['generating_sources_unchanged']=sources=={n:base.sha256(ROOT/'qa/week16'/n) for n in SOURCES}
            base.atomic_json(folder/'metadata.json',meta)
            if not meta['generating_sources_unchanged']:raise RuntimeError('Generating sources changed')
    if failure is not None:raise failure
    if not meta['converged'] or not meta['physical_plausibility_passed']:
        raise RuntimeError('Unchanged NASA numerical/physical acceptance checks failed')
    return meta


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--level',type=float,choices=[1.5,2.],required=True)
    p.add_argument('--iterations',type=int,choices=[8000],default=8000);p.add_argument('--mesh-only',action='store_true')
    print(json.dumps(run(**vars(p.parse_args())),indent=2))
