#!MC 1200
# Created by Tecplot 360 build 14.0.0.25119
$!VarSet |root| = 'shiftavg_553_578-580'
$!READDATASET  '"|root|.out" '
  READDATAOPTION = NEW
  RESETSTYLE = YES
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
  INITIALPLOTTYPE = XYLINE
  VARNAMELIST = '"V1" "V2" "V3" "V4" "V5"'
$!ALTERDATA 
  EQUATION = '{x}={V1}+124.748+26.2945'
$!ALTERDATA 
  EQUATION = '{y}={V3}'
$!ALTERDATA 
  EQUATION = '{z}={V5}'
$!ALTERDATA 
  EQUATION = '{dp/pinf}={V2}'
$!DUPLICATEZONE 
  SOURCEZONE = 1
  DESTINATIONZONE = 2
$!DUPLICATEZONE 
  SOURCEZONE = 1
  DESTINATIONZONE = 3
$!ALTERDATA  [2]
  EQUATION = '{dp/pinf}={V2}+{V5}'
$!ALTERDATA  [3]
  EQUATION = '{dp/pinf}={V2}-{V5}'
$!RENAMEDATASETZONE
  ZONE = 1
  NAME = 'WT'
$!RENAMEDATASETZONE
  ZONE = 2
  NAME = 'WT + Uncertainty'
$!RENAMEDATASETZONE
  ZONE = 3
  NAME = 'WT - Uncertainty'
$!WRITEDATASET  "|root|.plt"
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  ASSOCIATELAYOUTWITHDATAFILE = NO
  VARPOSITIONLIST =  [6-9]
  BINARY = NO
  USEPOINTFORMAT = YES
  PRECISION = 9
  TECPLOTVERSIONTOWRITE = TECPLOTCURRENT
